### ISSUE TITLE
CELLPOSE: ImportError: DLL load failed while importing cv2: The specified module could not be found.

### ISSUE THREAD

**Issue by jamnickn** [d2l-ai/d2l-en#2436]
ImportError: DLL load failed while importing cv2: The specified module could not be found.

I keep trying to open Cellpose. I have installed every package associated with cv2 on conda. Any advice? 

(cellpose) PS C:\Users\jamnickn> python -m cellpose
Traceback (most recent call last):
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 5, in <module>
    from cellpose import utils, models, io, core, version_str
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 5, in <module>
    import cv2
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.

**Comment by jamnickn** [comment]
(cellpose) PS C:\Users\jamnickn> conda list
# packages in environment at C:\Users\jamnickn\Anaconda3\envs\cellpose:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
cellpose                  2.2                      pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.0.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
fastremap                 1.13.3                   pypi_0    pypi
google-api-core           2.11.0                   pypi_0    pypi
google-auth               2.16.0                   pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.7.0                    pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.4.1                    pypi_0    pypi
googleapis-common-protos  1.58.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.1.23                pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
natsort                   8.2.0                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
opencv-python-headless    4.7.0.68                 pypi_0    pypi
openssl                   3.0.7                hcfcfb64_2    conda-forge
packaging                 23.0                     pypi_0    pypi
pip                       23.0               pyhd8ed1ab_0    conda-forge
protobuf                  4.21.12                  pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyqt5                     5.15.8                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqtgraph                 0.13.1                   pypi_0    pypi
python                    3.8.16          h4de0772_1_cpython    conda-forge
qtpy                      2.3.0                    pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
superqt                   0.4.1                    pypi_0    pypi
tifffile                  2023.1.23.1              pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
torch                     1.13.1                   pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.12.0                   pypi_0    pypi
