### ISSUE TITLE
It prompts ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by archerbj** [d2l-ai/d2l-en#2472]
```
from d2l import torch as d2l
```

```
Traceback (most recent call last):
  File "/xxx/pytorch/linear_regression/linear_regression.py", line 6, in <module>
    from d2l import torch as d2l
  File "/xxx/miniconda3/envs/d2l/lib/python3.9/site-packages/d2l/torch.py", line 32, in <module>
    import pandas as pd
  File "/xxx/miniconda3/envs/d2l/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/xxx/miniconda3/envs/d2l/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
(d2l) 
```

Neither the master branch nor 2.0.0 release can fix this issue 

and 
d2l==1.0.0b0   prompts
```
ERROR: Could not find a version that satisfies the requirement gym==0.21.0 (from d2l) (from versions: none)
ERROR: No matching distribution found for gym==0.21.0
```

Versions:
python: 3.9.16
d2l: 0.17.6

**Comment by BugMaker11** [comment]
我也遇到了这个问题，并找到了解决办法。你可以参考issue2182，，简单来说可以通过更新d2l解决。更新命令：pip install d2l==1.0.0-alpha0
